"""Adds phone number, image and jersey number columns

Revision ID: 0a0537be36ce
Revises: 21dd1946f959
Create Date: 2023-11-05 19:20:38.549717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0537be36ce'
down_revision = '21dd1946f959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('headshot_img_url', sa.String(), nullable=True))

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_phone_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('jersey_num', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('headshot_img_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('headshot_img_url')
        batch_op.drop_column('jersey_num')
        batch_op.drop_column('parent_phone_number')

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_column('headshot_img_url')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
