"""Adds gender column to Player class

Revision ID: 21dd1946f959
Revises: f6a6ce27e096
Create Date: 2023-10-29 20:09:09.522494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21dd1946f959'
down_revision = 'f6a6ce27e096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
