"""Changed column names: duration to notes and start_time to event_time

Revision ID: f6a6ce27e096
Revises: 0df8d3499249
Create Date: 2023-10-27 14:51:48.731886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a6ce27e096'
down_revision = '0df8d3499249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))
        batch_op.drop_column('start_time')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.INTEGER(), nullable=True))
        batch_op.drop_column('notes')
        batch_op.drop_column('event_time')

    # ### end Alembic commands ###
